### ISSUE TITLE
breaks page templates

### ISSUE THREAD

**Issue by pbearne** [Automattic/babble#193]
if you set a custom template for a static home page or have a front-page.php file with babble turned on neither are used

running dev branch

**Comment by yoavf** [comment]
Confirmed - running into this with 1.4.4.

I've set a custom page as the home page, front-page.php exists, and I get a 404 on the site root.

Here's the WP_Query sql as reported by the debug bar:

`SELECT wp_posts.* FROM wp_posts WHERE 1=1 AND (wp_posts.ID = '0') AND wp_posts.ID = 9 AND wp_posts.post_type = 'page' ORDER BY wp_posts.post_date DESC`

Post ID 9 is the page I've set as the home page in the site settings.

**Comment by simonwheatley** [comment]
@pbearne We believe this is fixed in the latest develop branch, would you mind trying that out and seeing if it's fixed for you, please? I'll close this issue for now, but reopen it if you still encounter the problem.
