### ISSUE TITLE
`is_rtl` considered harmful

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/babble#216]
Currently our [`is_rtl`](https://github.com/Automattic/babble/blob/d1649c2067a9a2a010ddb74105e823e5f32d5c22/class-languages.php#L445-L461) function parses (eugh) any locale file and checks for RTL. Instead we should just hardcode the RTL languages into an array (really, how often is a new one going to come along), and allow the dev to filter it so they can add any special case they may require.

**Comment by markoheijnen** [comment]
Why do we have `is_rtl`? Is this value needed or can it be dealt with on runtime?

**Comment by simonwheatley** [comment]
See this issue suggesting using Glotpress' locale class, which @hewsut has also just suggested: https://github.com/Automattic/babble/issues/76

Also relevant, this PR from December to add language install capabilities: https://github.com/Automattic/babble/pull/201

**Comment by simonwheatley** [comment]
> Why do we have `is_rtl`? Is this value needed or can it be dealt with on runtime?

I think this is just so we can have the information in the available languages screen. At runtime it's dealt with by loading the language locale information, not doing some crazy parsing of PHP to avoid loading it. :smile:

**Comment by markoheijnen** [comment]
I thought so, so if it's only for showing information then why bot removing it? I assume the user would know if the language is RTL or not ;)

**Comment by simonwheatley** [comment]
Removing it is another solution. *Thinking.*

**Comment by simonwheatley** [comment]
Hard coding a list of languages in Babble in some way, seems best.

**Comment by nb** [comment]
It’s a pity [GlotPress’s list](https://glotpress.trac.wordpress.org/browser/trunk/locales/locales.php) still isn’t in core:
- https://core.trac.wordpress.org/ticket/13069
- https://core.trac.wordpress.org/ticket/19600

**Comment by johnbillion** [comment]
I'd completely forgotten that core uses an `ltr` string for specifying text direction. Maybe Babble should switch to that.

I'll check the RTL languages for core and see if they all use it.

**Comment by johnbillion** [comment]
Closing in favour of #216

**Comment by willmot** [comment]
@johnbillion you closed this in favour of itself?

**Comment by johnbillion** [comment]
Whoops, #298

**Comment by simonwheatley** [comment]
> @johnbillion you closed this in favour of itself?

Where's the ‘like’ button on this thing?

**Comment by willmot** [comment]
@simonwheatley https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd
