### ISSUE TITLE
Don't blindly throw exceptions, as they'll fatal if not caught

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/babble#218]
Instead we should wrap all `exceptions` in checks for `WP_DEBUG`, so we do want this:

```php
if ( defined( 'WP_DEBUG ) && WP_DEBUG ) {
    throw new exception( 'WAAAAAH!' );
}
```

We do NOT want this:

```php
throw new exception( 'WAAAAAH!' );
```

**Comment by joehoyle** [comment]
For WordPress consistency is there a case for switching to the return WP_Error method of doing this? I've usually found Exceptions to be a bit of a hack in tightly knit wordpress code, though I know they have distinct advantages.

**Comment by simonwheatley** [comment]
Good point. Yep, I'd be happy moving to `WP_Error` instead.
