### ISSUE TITLE
Use `$url` parameter in `bbl_locale::home_url()`?

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/babble#221]
Investigate whether the `home_url` method in [`class-locale.php`](https://github.com/Automattic/babble/blob/develop/class-locale.php#L321-L329) can operate on the `$url` parameter instead of the returned value from the `get_option` call.

Check this does not break compatibility with WordPress multisite in a subdirectory mode.

**Comment by johnbillion** [comment]
Looks like I hadn't commented here, but the tests introduced in #279 demonstrate that the `$url` parameter cannot be used. If it's changed, the tests fail.
