### ISSUE TITLE
Remove `class-plugin.php` 

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/babble#222]
Most classes in Babble extend `Babble_Plugin` purely to use it's helper functions. Instead we should use core functions and APIs directly, and remove the `Babble_Plugin` class completely.

Steps:

* [x] Convert all `$this->add_[action|filter]` calls to `add_[action|filter]`
* [x] Remove methods `add_action` and `add_filter` from `Babble_Plugin`
* [x] Identify other methods in `Babble_Plugin` used elsewhere and convert
* [ ] Convert method usage to static or, where possible/appropriate, remove and convert to core APIs
* [ ] Stop extending `Babble_Plugin` everywhere it's used
* [x] Profit

**Comment by simonwheatley** [comment]
See: https://github.com/Automattic/babble/pull/214

**Comment by simonwheatley** [comment]
As part of removing the plugin class, we should remove all activation and deactivation hooks.

See also https://github.com/Automattic/babble/issues/242

**Comment by johnbillion** [comment]
I think this ticket has gone about as far as it can now. PR #314 removes a whole load of unused code, and removes the `Babble_Plugin` dependency from most classes.

The `Babble_Jobs`, `Babble_Languages`, `Babble_Switcher_Interface`, and `BabbleTranslationGroupTool` classes use the `render_admin()` and `get_option()` methods of this class so it makes sense that it remains. The methods in the `Babble_Plugin` class could all be converted to static methods, but we don't gain much from this.

**Comment by simonwheatley** [comment]
Agreed, thanks @johnbillion
