### ISSUE TITLE
We hook into `pre_update_option_rewrite_rules` which is probably suboptimal

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/babble#233]
Currently we hook into the pre update filter on the `rewrite_rules` option on `Babble_Locale::internal_rewrite_rules_filter()`, which is a little suboptimal.

Instead we should use the `rewrite_rules_array` filter to make our changes.

**Comment by johnbillion** [comment]
IIRC the pre update filter is used rather than `rewrite_rules_array` to ensure Babble hooks in as late as possible. A late priority on `rewrite_rules_array` should be sufficient though.
