### ISSUE TITLE
Add filter `home_url` – why is this here?

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/babble#235]
See:

* [x] https://github.com/Automattic/babble/blob/029bc70350d3195ce52e166877f74bf218d32dbe/class-locale.php#L292
* [x] https://github.com/Automattic/babble/blob/029bc70350d3195ce52e166877f74bf218d32dbe/class-locale.php#L304

Questions:

* Why actually is that there?
* Does it need to be there?
* Can we remove either or both?

**Comment by simonwheatley** [comment]
Also look at whether the `home_url` filtering, in the `Babble_Locale` class, is actually optimal.

**Comment by simonwheatley** [comment]
Fixed line references in the issue description by referencing a specific commit version of the file

**Comment by joehoyle** [comment]
From what I understand, these filters are needed as illustrated by the above Pull Request for the behat test. However, perhaps we wan't to just comment the code a bit better?

**Comment by joehoyle** [comment]
I've added more docs to the hooked functions in #315 to explain why the filters are there.

**Comment by joehoyle** [comment]
@simonwheatley over to you to merge #315 which should conclude this issue.
