### ISSUE TITLE
Translator role cannot access the translation jobs

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/babble#237]
Pretty major problem. :frowning: 

1. Log in as a translator
2. Select "Translations" from the admin menu
3. Hit an error, rather than seeing translation jobs

> "You do not have sufficient permissions to access this page."

**Comment by markoheijnen** [comment]
Seems I forgot to mention this. To specify, you can't access the translation job from someone else. Your own ones should be fine.

**Comment by simonwheatley** [comment]
@markoheijnen I'm seeing this error for accessing the list of translation jobs, at `/wp-admin/edit.php?post_type=bbl_job`. So the list table screen. Is that what you're seeing? Are you saying that if you have a job on that screen it works? 

Any ideas for a fix?

Note I've just tested this and replicated as far back as WP 3.9 so far.

**Comment by markoheijnen** [comment]
I meant a different issue. Mine is for editors. I totally forgot about the fact that there is a translator role.
The problem there hacky solvable to give all bbl_ permissions to the editors role.

**Comment by simonwheatley** [comment]
@markoheijnen Stick an issue in for your issue. :smile:

**Comment by markoheijnen** [comment]
Will do tomorrow with hopefully also a fix :wink:

**Comment by simonwheatley** [comment]
:+1:

**Comment by simonwheatley** [comment]
Narrowed this down a bit; when I comment out some of the code in the filter on `user_has_cap`, the translator is able to access the jobs list again. /cc @johnbillion 

```php
case 'edit_post':
case 'edit_bbl_job':
case 'delete_post':
case 'delete_bbl_job':
case 'publish_post':
case 'publish_bbl_job':
```

**Comment by simonwheatley** [comment]
Hmmm. I'm mistaken, it's not that code block.

**Comment by johnbillion** [comment]
A while ago I tracked this down to the `remove_submenu_page()` call in `Babble_Jobs::admin_menu()`. Removing it reinstates access to that menu for all users, but I haven't determined the exact cause. I waded into WordPress' menu code briefly, but soon backed out.

This looks similar to core bug [#22895](https://core.trac.wordpress.org/ticket/22895).
