### ISSUE TITLE
WordPress 4.4 caused menu items to disappear  

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/babble#350]
There's something going on the function registered_post_type around https://github.com/Automattic/babble/blob/develop/class-post-public.php#L258 which is causing the Jetpack Portfolio (CPT) menu to disappear on a WordPress.com VIP client site. This issue appears related to a recent core merge and may have to do with how the `public` and/or `show_ui` args are handled.

The conditional here seems intended to avoid creating shadow post_types for non-public post types:

```
    // Don't bother with non-public post_types for now
    // @FIXME: This may need to change for menus?
    if ( false === $args->public )
        return;
```

I theorize that the issue may be that the "feedback" post type on WordPress.com is non-public, but has show_ui == true, which seems to throw off the menu generation. Perhaps this has to do with a 4.4 change to the register_post_type function, described as "4.4.0 The `show_ui` argument is now enforced on the post type listing screen and post editing screen."

I haven't tested thoroughly, but changing the conditional like so seems to resolved it:

```
    // Don't bother with post_types that are BOTH non-public and non-show_ui for now
    // Updated to deal with a 4.4 incompatibility
    // @FIXME: This may need to change for menus?
    if ( false === $args->public && false === $args->show_ui )
        return;
```

Let me know how I can help ;-)

**Comment by joshbetz** [comment]
I think this is related to Babble clobbering some arguments for already registered post types, here:

https://github.com/Automattic/babble/blob/develop/class-post-public.php#L277-L285

**Comment by emrikol** [comment]
I think @joshbetz is on to something.  Babble is overwriting `menu_position` when calling `register_post_type()`, which causes the shadow post types to overwrite the position of the standard post type, and _then_ the shadow post type is removed from the menu in `Babble_Post_Public::add_menu_classes()`

This can be tested easily with this patch:

```
Index: class-post-public.php
===================================================================
--- class-post-public.php       (revision 224474)
+++ class-post-public.php       (working copy)
@@ -325,6 +325,9 @@
                                $new_args['capabilities']['create_posts'] = 'do_not_allow';
                        }

+                       // Unset menu_position so that shadow post types won't overwrite post types with a hard coded position.
+                       unset( $new_args['menu_position'] );
+
                        $result = register_post_type( $new_post_type, $new_args );
                        if ( is_wp_error( $result ) ) {
                                bbl_log( "Error creating shadow post_type for $new_post_type: " . print_r( $result, true ), true );
```

I'm not sure what changed in 4.4 that causes this to happen though.
